### ISSUE TITLE
fonts.conf 导致 Chromium 部分网站页面显示异常

### ISSUE THREAD

**Issue by SharerMax** [szclsya/dotfiles#4]
Liberation 字体替换后导致 Chromium 部分网站页面显示异常。 如 [reddiet](https://www.reddit.com/)
![image](https://github.com/szclsya/dotfiles/assets/9065684/adb61f7d-c99c-426f-9f67-b5f23ce00a89)
![image](https://github.com/szclsya/dotfiles/assets/9065684/689589e0-b571-418d-ad78-7225f48b4773)

``` css
:root {
--font-sans: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,'Apple Color Emoji','Segoe UI Emoji','Segoe UI Symbol',sans-serif
}
```
删除 ``` 'Apple Color Emoji','Segoe UI Emoji' ``` 后显示正常
